Runtime Error at Fri Feb 26 10:18:29 2016:
错误
执行时段错误：*call_other() couldn't find object

程式：/adm/daemons/cmd_d.c 第 15 行
物件: /adm/daemons/cmd_d
对象：/obj/user#0
呼叫来自：/obj/user.c 的 cmd_hook() 第 40 行，物件： /obj/user#0
呼叫来自：/adm/daemons/cmd_d.c 的 do_cmd() 第 15 行，物件： /adm/daemons/cmd_d

